# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_report_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='report_period',
        ),
    ]
